insert into Users
    (userName, picture, bio, answers)
values
    ("Christopher Hemsworth", "bringd0wntheMjolnir", "https://pixel.nymag.com/imgs/fashion/daily/2017/07/25/Chris-Hemsworth/25-Chris-Hemsworth.w330.h412.jpg", "Native Australian here, so you know I’m good at wrestling with any dangerous animal out there. Not only am I a nerd, but I’ve starred in movies in the Marvel Cinematic Universe (MCU) as a Norse God. I have access to a bunch of the movie props and you could possibly meet some of my other MCU friends if we were to date. Born in Australia, I also love to do non-nerdy things, such as surfing and jogging on the beach. I am not your typical nerd, but I do dress up pretty often."),
    ("Lyndsey Scott", "BeautywithBrains", "https://pbs.twimg.com/media/D1t7PZMU8AEhrR2.jpg", "I am an American model, who would like to turn around the stereotype that all models are just looks with no brains. As Calvin Klein’s first African-American exclusive model, I feel I have a lot to offer. I am one of the top iOS responders on Stack Overflow and have done tutorial videos for children with other well-known coders, such as Bill Gates and Mark Zuckerberg. My love for coding started at the age of 12 and I can code in various languages, some of them: Java, C++, Python, Objective C, and iOS. My dream is to inspire other young girls to get into software development and enter the field."),
    ("Grace Hopper", "NavyRulesArmyDr00l$", "https://www.engineerbabu.com/blog/wp-content/uploads/2016/12/grace-hopper-3-600x403-1.jpg", "I am an American computer scientist and Navy rear admiral. Due to my popularization of machine-independent programming languages, the development of COBOL was started. I also have my PhD in mathematics from Yale and was a mathematics professor. I always believed that programming in the English language was possible, so I built a compiler that converted English terms into machine code that is understood by computers. I also love to take things apart, to see how they work from the inside."),
    ("Natalie Portman", "TheProfessionalNerd", "http://images6.fanpop.com/image/photos/41600000/Natalie-Portman-natalie-portman-41650501-767-767.jpg", "You may not think of me as a nerd, being an American actress in so many movies. However, I have starred in the Star Wars franchise when I was only in high school and even missed the premiere of the movie to study for my finals. I also have attended Harvard, because I think education is important. I have also starred in the Marvel Cinematic Universe, making it so I have been in many nerdy universes. Animal rights and the environment are two of my current causes that I love to support."),
    ("Frances Elizabeth “Fran” Allen", "IBMfellowLady", "https://www.berkeley.edu/news/berkeleyan/2008/01/images/franallen1.jpg", "I am an American computer scientist and known for being a pioneer in optimizing compilers. I am also the first female IBM Fellow and the first woman to win the Turing award. I grew up on a farm, so I am really good with animals. However, I also have a background in teaching, so I am really good with kids also. Some of my other achievements include having my degree in mathematics, which helped me to lay down the groundwork for automatic program optimization technology.");
insert into Users
    (userName, picture, bio, answers)
values
    ("Sophie Wilson", "ItsSophieW", "https://upload.wikimedia.org/wikipedia/commons/b/b3/Sophie_Wilson.jpg", "Hello everyone. I hail from England, cheers m8. I designed the Acorn Micro-Computer, the first of a long line of computers sold by Acorn Computers Ltd, including its programming language BBC BASIC. I later designed the instruction set of the ARM processor, which is used in most 21st-century smartphones. I now serve as a director at the technology conglomerate Broadcom Inc."),
    ("Tom Preston-Werner", "TommyBoiii", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Tom_Preston-Werner.jpg/330px-Tom_Preston-Werner.jpg", "I am a software developer and entrepreneur. Additionally, I am an active contributor within the open-source development community, most prominently in the San Francisco Bay Area, where I live.
I am best known as the founder and former CEO of GitHub a Git repository web-based hosting service, which I co-founded in 2008. For fun I study cultural anthropology."),
    ("Rasmus Lerdof", "LilRasmus", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Rasmus_Lerdorf_August_2014_%28cropped%29.JPG/330px-Rasmus_Lerdorf_August_2014_%28cropped%29.JPG", "I am a Danish-Canadian programmer. I created the PHP scripting language, authoring the first two versions of the language and participated in the development of later versions. For fun I travel the world meeting all the other people named Rasmus out there."),
    ("Steve Wozniak", "FreakySteve", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Steve_Wozniak%2C_November_2018.jpg/330px-Steve_Wozniak%2C_November_2018.jpg", "I am an American inventor, electronics engineer, programmer, philanthropist, and technology entrepreneur who in 1976 co-founded a little company called Apple, maybe you’ve heard of it? I used to date Kathy Griffin. For fun I like playing Tetris and counting my money."),
    ("Brendan Eich", "BeautifulBrendan", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Brendan_Eich_Mozilla_Foundation_official_photo.jpg/330px-Brendan_Eich_Mozilla_Foundation_official_photo.jpg", "I am an American technologist and creator of the JavaScript programming language. I also co-founded the Mozilla project, the Mozilla Foundation and the Mozilla Corporation, and served as the Mozilla Corporation's chief technical officer and briefly its chief executive officer. I also have a company called SpiderMonkey-isn’t that a cool name?");
